[package]
name = "dao_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.17.1"
ic-cdk-macros = "0.17.1"
ic-stable-structures = "0.6.7"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
candid = "0.10"
